name: API Test and Deploy
on:
  push:
    - 'services/tasks_api/**'
    - '.github/workflows/api.yml'
jobs:
    code-quality:
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.10]
                poetry-version: [1.5.1]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                working-directory: services/tasks_api
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install poetry
              uses: abatilo/actions-poetry@v2
              with:
                poetry-version: ${{ matrix.poetry-version }}
            - name: Install dependencies
              run: poetry install --no-root
            - name: Run black
              run: poetry run black . --check
            - name: Run isort
              run: poetry run isort . --check-only
            - name: Run flake8
              run: poetry run flake8 .
            - name: Run bandit
              run: poetry run bandit .
              